version: "3.3"
services:
  api:
    build: .
    volumes:
      - "./src:/api/src"
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file: .env
    command: npm run dev
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"